[tool.uv]
package = false

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "test_model"
version = "0.1.0"
description = "Test model for Hugging Face"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "pandas",
    "numpy",
    "torch==2.6.0+cu126",
    "transformers>=4.51.0",
    "datasets",
    "tqdm",
    "matplotlib",
    "peft",
    "trl",
    "pyyaml",
    "deepspeed",
    "mpi4py>=4.0.3",
    "psutil>=7.0.0",
    "hf-xet>=1.0.3",
    "openai",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126"},
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true